// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Medicine identification AI agent.
 *
 * - identifyMedicine - A function that handles the medicine identification process.
 * - IdentifyMedicineInput - The input type for the identifyMedicine function.
 * - IdentifyMedicineOutput - The return type for the identifyMedicine function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const IdentifyMedicineInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo of a pill, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type IdentifyMedicineInput = z.infer<typeof IdentifyMedicineInputSchema>;

const IdentifyMedicineOutputSchema = z.object({
  medicineName: z.string().describe('The identified name of the medicine.'),
  confidence: z.number().describe('The confidence level of the identification (0-1).'),
});
export type IdentifyMedicineOutput = z.infer<typeof IdentifyMedicineOutputSchema>;

export async function identifyMedicine(input: IdentifyMedicineInput): Promise<IdentifyMedicineOutput> {
  return identifyMedicineFlow(input);
}

const identifyMedicinePrompt = ai.definePrompt({
  name: 'identifyMedicinePrompt',
  input: {schema: IdentifyMedicineInputSchema},
  output: {schema: IdentifyMedicineOutputSchema},
  prompt: `You are an expert pharmacist. Your job is to identify the medicine in the photo.

  Analyze the following image of a pill and identify the medicine, along with a confidence score.

  Photo: {{media url=photoDataUri}}
  `,
});

const identifyMedicineFlow = ai.defineFlow(
  {
    name: 'identifyMedicineFlow',
    inputSchema: IdentifyMedicineInputSchema,
    outputSchema: IdentifyMedicineOutputSchema,
  },
  async input => {
    const {output} = await identifyMedicinePrompt(input);
    return output!;
  }
);
