// This is an autogenerated file from Firebase Studio.
export const SESSION_COOKIE_NAME = '__session';

export const SESSION_COOKIE_OPTIONS = {
    httpOnly: true,
    secure: true,
    sameSite: 'lax' as const,
    path: '/',
};
