// This is an autogenerated file from Firebase Studio.
import { auth as adminAuth } from 'firebase-admin';
import { NextRequest, NextResponse } from 'next/server';
import { SESSION_COOKIE_OPTIONS, SESSION_COOKIE_NAME } from '@/lib/session';

export async function GET(request: NextRequest) {
    const authorization = request.headers.get('Authorization');
    const idToken = authorization?.split('Bearer ')[1];

    if (!idToken) {
        return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    try {
        const expiresIn = 60 * 60 * 24 * 5 * 1000;
        const sessionCookie = await adminAuth().createSessionCookie(idToken, { expiresIn });
        
        return NextResponse.json({
            sessionCookie,
            options: SESSION_COOKIE_OPTIONS,
        });
    } catch (error) {
        console.error('Error creating session cookie:', error);
        return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
    }
}
